// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 5/13/2026, 11:37:13 PM
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.js";
const config = [
{"content":{"files":["D:/Webtruyen/frontend/components/**/*.{vue,js,jsx,mjs,ts,tsx}","D:/Webtruyen/frontend/components/**/*.{vue,js,jsx,mjs,ts,tsx}","D:/Webtruyen/frontend/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","D:/Webtruyen/frontend/plugins/**/*.{js,ts,mjs}","D:/Webtruyen/frontend/composables/**/*.{js,ts,mjs}","D:/Webtruyen/frontend/utils/**/*.{js,ts,mjs}","D:/Webtruyen/frontend/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","D:/Webtruyen/frontend/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","D:/Webtruyen/frontend/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","D:/Webtruyen/frontend/app.config.{js,ts,mjs}"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;